men/urls.py
from django.urls import path

from men import views

app_name = 'men'

urlpatterns = [
    path('home/', views.HomePageView.as_view(), name='home'),
    path('create-post/', views.CreateFormView.as_view(), name='post_create'),
    path('communicate/', views.SendEmailPageView.as_view(), name='communicate'),
    path('about-site/', views.AboutSitePageView.as_view(), name='about-site'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('detail/<slug:post_slug>/', views.DetailPageView.as_view(), name='post_detail'),
    path('category/<slug:cat_slug>/', views.CatPageList.as_view(), name='category'),
    path('tags/<slug:tag_slug>/', views.TagPageList.as_view(), name='tag'),
]

sitemen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('men/', include('men.urls', namespace='men')),
    path('users/', include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    # path('registration/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users import views

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'
    ), name='password_change_done'),
    path('profile/', views.ProfileUserView.as_view(), name='profile'),
    path('profile_edit/', views.ProfileEditUserView.as_view(), name='profile_edit'),
    path('register/', views.RegisterUserView.as_view(), name='register'),

    path("password_reset/", PasswordResetView.as_view(
        template_name="users/password_reset_form.html",
        email_template_name="users/password_reset_email.html",
        success_url=reverse_lazy("users:password_reset_done"),
    ), name="password_reset"),

    path("password_reset/done/",
         PasswordResetDoneView.as_view(
             template_name="users/password_reset_done.html"
         ), name="password_reset_done",
         ),

    path("reset/<uidb64>/<token>/",
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete"),
         ), name="password_reset_confirm",
         ),
    path("reset/done/",
         PasswordResetCompleteView.as_view(
             template_name="users/password_reset_complete.html"
         ),
         name="password_reset_complete",
         ),
]

templates/include/footer.html
<div class="container">
    <footer class="footer">
        <ul class="nav justify-content-center border-bottom pb-3">
            <li class="nav-item"><a href="{% url 'men:home' %}" class="nav-link px-2 text-body-secondary">Главная</a>
            </li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
            <li class="nav-item"><a href="{% url 'men:about-site' %}" class="nav-link px-2 text-body-secondary">О
                сайте</a></li>
        </ul>
        <p class="text-center text-body-secondary">© 2023 Company, Inc</p>
    </footer>
</div>

templates/include/header.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary nav-color
">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'men:home' %}">
            <img class="logo-img" src="{% static 'men/image/logo.png' %}" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 menu">
                <li class="nav-item menu-li fs-6">
                    {% url 'men:home' as url %}
                    <a href="{{ url }}"{% if request.path == url %}
                       class="active-btn nav-link fs-6"

                    {% else %}
                       class="nav-link fs-6"
                    {% endif %}
                       aria-current="page">Главная</a>
                </li>
                <li class="nav-item menu-li">
                    {% url 'men:post_create' as url %}
                    <a href="{{ url }}"{% if request.path == url %}
                       class="active-btn nav-link fs-6"
                    {% else %}
                       class="nav-link fs-6"
                    {% endif %} aria-current="page">Добавить статью</a>
                </li>
                <li class="nav-item menu-li">
                    {% url 'men:communicate' as url %}
                    <a href="{{ url }}"{% if request.path == url %}
                       class="active-btn nav-link fs-6"
                    {% else %}
                       class="nav-link fs-6"
                    {% endif %} aria-current="page">Обратная связь</a>
                </li>
                <li class="nav-item menu-li">
                    {% url 'men:about-site' as url %}
                    <a href="{{ url }}"{% if request.path == url %}
                       class="active-btn nav-link fs-6"
                    {% else %}
                       class="nav-link fs-6"
                    {% endif %} aria-current="page">О сайте</a>
                </li>

            </ul>
            {% if user.is_authenticated %}
                {% include 'include/search_include.html' %}
                <div class="ms-2 h-15">
                <span class="badge d-flex align-items-center p-1 pe-2 text-success-emphasis bg-success-subtle border border-success-subtle rounded-pill">
                    <a href="{% url 'users:profile' %}" class="text-dark" title="Личный кабинет"
                       data-bs-toggle="tooltip" data-bs-placement="bottom" title="Личный кабинет">
                        {% if request.user.photo.url != None %}
                            <img class="rounded-circle me-1" width="26" height="26" src="{{ user.photo.url }}" alt="">
                        {% elif user.social_auth %}
                            <img class="rounded-circle me-1" width="26" height="26"
                                 src="https://github.com/{{ user.username }}.png" alt="">
                        {% else %}
                            <img class="rounded-circle me-1" width="26" height="26" src="https://github.com/mdo.png"
                                 alt="">
                        {% endif %}
                        {{ request.user.first_name|title|default:request.user }}
                    </a>
                    <span class="vr mx-2"></span>
                    <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm" style="height: 34px"
                                data-bs-toggle="tooltip" data-bs-placement="bottom" title="Выход">
                           <i style="font-size: 1.1rem" class="bi bi-box-arrow-right">
                           </i>
                        </button>
                    </form>
                </span>
                </div>
            {% else %}
                <div class="ms-2 p-3 w-15 reg_open">
                    <span class="badge d-flex align-items-center p-1 pe-2 text-light-emphasis bg-light-subtle border border-dark-subtle rounded-pill">
                        <a href="{% url 'users:login' %}" class="text-dark w-25 fs-6">Войти</a>
                         <span class="vr mx-2"></span>
                        <a href="{% url 'users:register' %}" class="text-dark w-50 fs-6">Регистрация</a>
                     </span>
                </div>
            {% endif %}
        </div>
    </div>
</nav>

templates/include/left_block.html
<div class="row">
    <ul class="mt-4 bg-primary-subtle p-0 bl-top">
        <li class="list-group-item bg-primary-subtle p-0">
            {% url 'men:home' as url %}
            <a href="{{ url }}"{% if request.path == url %}
               class="btn link-info border-0"
            {% else %}
               class="btn border-0"
            {% endif %}
               aria-current="page">Все категории</a>
        </li>
        <hr class="hr"/>
        {% for cat in category %}
            <li class="list-group-item bg-primary-subtle ps-3">
                <a href="{{ cat.get_absolute_url }}"
                   class="
                   btn border-0
                   {% if cat.id == cat_id.id %}link-info{% endif %}">
                    {{ cat.name }}
                </a>
            </li>
        {% endfor %}
        <hr class="hr"/>
    </ul>
</div>

<div class="row">
    <ul class="mt-4 d-flex flex-wrap bg-primary-subtle p-0 bl-top">
        <li class="list-group-item ms-2 bg-primary-subtle col-10">
            <em>
                Теги:
            </em>
        </li>
        <hr class="hr"/>
        {% for tag in tags %}
            <li class="list-group-item bg-primary-subtle ps-3 ">
                <a
                        href="{{ tag.get_absolute_url }}"
                        class="btn border-2 rounded-0 m-1 p-1 shadow
                        {% if tag.id == tag_id.id %}
                        link-info border-danger
                        {% else %}
                        border-black
                        {% endif %}
                             ">
                    {{ tag.name|title }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

templates/include/paginate.html
{% if page_obj.has_other_pages %}
    <p class="mt-2">Показанно с {{ page_obj.start_index }} по {{ page_obj.end_index }} всего {{ page_obj.paginator.count }} статей</p>
    <div class="row mt-4">
        <div class="paginate offset-md-2">
            <nav aria-label="">
                <ul class="pagination">
                    <li class="page-item">
                        {% if page_obj.has_previous %}
                            <a class="page-link" href="?page=1">
                                Первая
                            </a>
                            </li>
                            <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                               aria-label="Предыдущая">
                                <span aria-hidden="true">«</span>
                            </a>
                        {% endif %}
                        </li>
                    {% for page in page_obj.paginator.page_range %}
                        {% if page_obj.number == page %}
                            <li class="page-item">
                                <a class="page-link disabled bg-primary text-white"
                                   href="?page={{ page }}">{{ page }}</a>
                            </li>
                        {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Следующая">
                                <span aria-hidden="true">»</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" data-bs-toggle="tooltip" data-bs-placement="top" title="Передти на {{ page_obj.paginator.num_pages }}" href="?page={{ page_obj.paginator.num_pages }}">
                                Последняя
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endif %}

templates/include/search_include.html
<form class="d-flex" role="search" method="get" name="" action="{% url 'men:search' %}">
    <input class="form-control me-auto" type="text" name="search" placeholder="Поиск....."
           aria-label="Ваш поиск.....">
    <button class="btn btn-success ms-2" type="submit">Search</button>
</form>

templates/include/search_paginate.html
{% if page_obj.has_other_pages %}
        <p>Показанно с {{ page_obj.start_index }} по {{ page_obj.end_index }} всего {{ page_obj.paginator.count }} статей</p>
    <div class="row mt-4">
        <div class="paginate offset-md-2">
            <nav aria-label="">
                <ul class="pagination">
                    <li class="page-item">
                        {% if page_obj.has_previous %}
                            <a class="page-link" href="?page=1&{{ query_params }}">
                                Первая
                            </a>
                            </li>
                            <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ query_params }}"
                               aria-label="Предыдущая">
                                <span aria-hidden="true">«</span>
                            </a>
                        {% endif %}
                        </li>
                    {% for page in page_obj.paginator.page_range %}
                        {% if page_obj.number == page %}
                            <li class="page-item">
                                <a class="page-link disabled bg-primary text-white"
                                   href="?page={{ page }}">{{ page }}</a>
                            </li>
                        {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page }}&{{ query_params }}">{{ page }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ query_params }}" aria-label="Следующая">
                                <span aria-hidden="true">»</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" data-bs-toggle="tooltip"
                               data-bs-placement="top"
                               title="всего {{ page_obj.paginator.num_pages }}"
                               href="?page={{ page_obj.paginator.num_pages }}&{{ query_params }}">
                                Последняя
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endif %}