men/urls.py
from django.urls import path

from men import views

app_name = 'men'

urlpatterns = [
    path('home/', views.HomePageView.as_view(), name='home'),
    path('create-post/', views.CreateFormView.as_view(), name='post_create'),
    path('communicate/', views.SendEmailPageView.as_view(), name='communicate'),
    path('about-site/', views.AboutSitePageView.as_view(), name='about-site'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('detail/<slug:post_slug>/', views.DetailPageView.as_view(), name='post_detail'),
    path('category/<slug:cat_slug>/', views.CatPageList.as_view(), name='category'),
    path('tags/<slug:tag_slug>/', views.TagPageList.as_view(), name='tag'),
]

sitemen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('men/', include('men.urls', namespace='men')),
    path('users/', include('users.urls', namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    # path('registration/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users import views

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'
    ), name='password_change_done'),
    path('profile/', views.ProfileUserView.as_view(), name='profile'),
    path('profile_edit/', views.ProfileEditUserView.as_view(), name='profile_edit'),
    path('register/', views.RegisterUserView.as_view(), name='register'),

    path("password_reset/", PasswordResetView.as_view(
        template_name="users/password_reset_form.html",
        email_template_name="users/password_reset_email.html",
        success_url=reverse_lazy("users:password_reset_done"),
    ), name="password_reset"),

    path("password_reset/done/",
         PasswordResetDoneView.as_view(
             template_name="users/password_reset_done.html"
         ), name="password_reset_done",
         ),

    path("reset/<uidb64>/<token>/",
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete"),
         ), name="password_reset_confirm",
         ),
    path("reset/done/",
         PasswordResetCompleteView.as_view(
             template_name="users/password_reset_complete.html"
         ),
         name="password_reset_complete",
         ),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True, verbose_name='Фотография')
    date_of_bird = models.DateTimeField(blank=True, null=True, verbose_name='День рождения')

users/forms.py
from datetime import datetime
from django.utils import timezone
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control', 'id': 'floatingInput',
                                   'placeholder': 'name@example.com',
                               }))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={
                                   'class': 'form-control', 'id': 'floatingPassword',
                                   'placeholder': 'Password', 'type': 'Password',
                               }))
    remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control', 'id': 'floatingInput',
                                   'placeholder': 'name@example.com',
                               }
                               )
                               )
    email = forms.CharField(label='E-mail',
                            required=False,
                            widget=forms.TextInput(attrs={
                                'class': 'form-control', 'id': 'floatingInput',
                                'placeholder': 'name@example.com',
                            }
                            )
                            )
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control', 'id': 'floatingPassword',
                                    'placeholder': 'Password', 'type': 'Password',
                                }))
    password2 = forms.CharField(label='Повтор пароля',
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control', 'id': 'floatingPassword',
                                    'placeholder': 'Password', 'type': 'Password',
                                }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'floatingInput',
        'placeholder': 'name@example.com',
    }
    ), required=False)
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'floatingInput',
        'placeholder': 'name@example.com',
    }
    ), required=False)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой E-mail уже существует')
        return email


class UserPasswordChangeForm(PasswordChangeForm):
    new_password1 = forms.CharField(
        label="Новый пароль",
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
    )
    new_password2 = forms.CharField(
        label="Повторите новый пароль",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )
    old_password = forms.CharField(
        label="Старый пароль",
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", "autofocus": True}
        ),
    )


class ProfileUserForms(forms.ModelForm):
    username = forms.CharField(
        disabled=True,
        label='Логин',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'name@example.com',
        }
        )
    )
    email = forms.CharField(
        disabled=True,
        required=False,
        label='E-mail',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'floatingInput',
            'placeholder': 'name@example.com',
        }
        ))

    this_year = timezone.now().year
    date_of_bird = forms.DateField(
        label='День рождения',
        widget=forms.SelectDateWidget(
            years=tuple(range(this_year - 100, this_year - 5))
        ))

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'date_of_bird', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'floatingInput',
                'placeholder': 'name@example.com',
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'floatingInput',
                'placeholder': 'name@example.com',
            }),

            'photo': forms.ClearableFileInput(attrs={
                'class': 'text-center center-block file-upload'
            }),
        }

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import TemplateView

from .forms import LoginUserForm, RegisterUserForm, UserPasswordChangeForm, ProfileUserForms


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'



class LogoutUserView(LogoutView):
    template_name = 'registration/logged_out.html'


class ProfileUserView(LoginRequiredMixin, TemplateView):
    template_name = 'users/profile.html'



class ProfileEditUserView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForms
    template_name = 'users/edit_profile.html'
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_object(self):
        return self.request.user


class RegisterUserView(CreateView):
    template_name = "users/register.html"
    form_class = RegisterUserForm
    success_url = reverse_lazy('men:home')

    def form_valid(self, form):

        # form.groups.add(name='hello')
        form.save()
        return super().form_valid(form)


class UserPasswordChange(PasswordChangeView):
    template_name = "users/password_change_form.html"
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

users/templates/users/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% load user_tags %}

{% block link %}

{% endblock %}

{% block title %}
    Настройка профиля
{% endblock %}

{% block content %}
    <div class="hr"></div>
    <div class="container bootstrap snippet">
        <div class="row">
            <div class="col-sm-10"><h1>{{ user.first_name }}</h1></div>
            <div class="col-sm-2">
                <a href="{% url 'men:home' %}" class="pull-right">
                    <img title="profile image" alt="Label" class="img-circle img-responsive"
                         src="http://www.gravatar.com/avatar/28fd20ccec6865e2d5f0e1f4446eb7bf?s=100">
                </a>
            </div>
        </div>
        <form class="form" method="post" id="registrationForm" enctype="multipart/form-data">
            <div class="row">
                <div class="col-sm-4"><!--left col-->


                    <div class="text-center">
                        {% if user.photo %}
                            <img src="{{ user.photo.url }}" alt=""
                                 class="avatar img-thumbnail">
                        {% elif user.social_auth %}
                            <img class="avatar img-thumbnail"
                                 src="https://github.com/{{ user.username }}.png" alt="">
                        {% else %}
                            <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png"
                                 class="avatar img-thumbnail"
                                 alt="avatar">
                        {% endif %}
                        {{ form.photo }}
                    </div>
                    </hr><br>
                    <ul class="list-group">
                        <li class="list-group-item text-muted">Активность <i class="fa fa-dashboard fa-1x"></i></li>
                        <li class="list-group-item text-right"><span
                                class="pull-left"><strong>Коментируемые</strong></span>
                            13
                        </li>
                        <li class="list-group-item text-right"><span class="pull-left"><strong>Постов</strong></span> 37
                        </li>
                    </ul>

                </div><!--/col-3-->
                <div class="col-sm-8">
                    <ul class="nav nav-tabs">
                        <p>Профиль</p>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="home">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="form-floating mt-2">
                                    {{ form.username }}
                                    <label for="floatingInput">Логин</label>
                                </div>
                                <div class="form-floating mt-2">
                                    {{ form.email }}
                                    <label for="floatingInput">E-mail</label>
                                </div>
                                <div class="form-floating mt-2">
                                    {{ form.first_name }}
                                    <label for="floatingInput">Имя</label>
                                </div>
                                <div class="form-floating mt-2">
                                    {{ form.last_name }}
                                    <label for="floatingInput">Фамилия</label>
                                </div>
                                <div class="form-floating mt-2">
                                     <span class="me-2">
                                      День рождения
                                     </span>
                                    {{ form.date_of_bird }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-12">
                                    <br>
                                    <button class="btn btn-lg btn-success" type="submit"><i
                                            class="glyphicon glyphicon-ok-sign"></i> Сохранить изменения
                                    </button>
                                    <button class="btn btn-lg" type="reset"><i class="glyphicon glyphicon-repeat"></i>
                                        Обновить
                                    </button>
                                </div>
                            </div>
                            <hr>
                        </div><!--/tab-pane-->
                    </div><!--/tab-pane-->
                </div><!--/tab-content-->
            </div><!--/col-9-->
        </form>
    </div><!--/row-->

{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'users/css/user_login.css' %}">
{% endblock %}

{% block title %}Вход{% endblock %}

{% block content %}

    {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
                <p>{{ error }}</p>
            {% endfor %}
        </div>
    {% endif %}
{% if form.error %}
1
{% endif %}

    <div class="row justify-content-center user_log">
        <main class="form-signin w-25 m-auto justify-content-center">
            {% if user.is_authenticated %}
                <div class="text-center">
                    <img class="mb-4" src="{% static 'men/image/logo.png' %}" alt="" width="72" height="57">

                    <h1 class="h3 mb-3 fw-normal">Вы уже авторизованы</h1>
                </div>
            {% else %}
                <div class="text-center">
                    <form method="post" class="">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}"/>
                        <img class="mb-4" src="{% static 'men/image/logo.png' %}" alt="" width="72" height="57">

                        <h1 class="h3 mb-3 fw-normal">Авторизация</h1>
                        {#                        {% if form.non_field_errors %}#}
                        {#                            {% for error in form.non_field_errors %}#}
                        {#                                <div class="alert alert-danger" role="alert">#}
                        {#                                    {{ error }}#}
                        {#                                </div>#}
                        {#                            {% endfor %}#}
                        {#                        {% endif %}#}

                        <div class="form-floating mt-2">
                            {{ form.username }}
                            <label for="floatingInput">Логин</label>
                        </div>
                        <div class="form-floating mt-2">
                            {{ form.password }}
                            <label for="floatingPassword">Пароль</label>
                        </div>
                            <div class="form-check text-start my-3">
                              {{ form.remember_me }}
                              <label class="form-check-label" for="flexCheckDefault">
                                запомнить меня
                              </label>
                            </div>
                        <button class="btn btn-primary w-100 py-2 mt-2" type="submit">Войти</button>
                        <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                        <div class="panel panel-default ">
                            <div class="panel-heading mt-3">Социальные сети</div>
                            <ul class="social-icon-style1 text-center d-flex list-unstyled ps-0">
                                <li>
                                    <a href="#!" class="p-2 text-danger fs-2"><i
                                            class="bi bi-pinterest"></i>
                                    </a>
                                </li>
                                <li>

                                    <a href="#!" class="p-2 text-warning fs-2"><i
                                            class="bi bi-instagram"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#!" class="p-2 text-success fs-2"><i
                                            class="bi bi-whatsapp"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'social:begin' 'github' %}" class="p-2 text-dark fs-2">
                                        <i class="bi bi-github"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <p class="mt-5 mb-3 text-body-secondary">© 2017–2024</p>
                    </form>
                </div>
            {% endif %}
        </main>

    </div>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block link %}
{% endblock %}

{% block title %}Успешное изменение пароля{% endblock %}

{% block content %}
    <div class="mt-5 ms-5">
        <h4>Ваш пароль успешно изменен !</h4>
        <p> вернуться в профиль по <a href="{% url 'users:profile' %}">ссылке</a></p>
    </div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" href="{% static "admin/css/forms.css" %}">{% endblock %}
{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
        &rsaquo; {% translate 'Password reset confirmation' %}
    </div>
{% endblock %}

{% block content %}
    {% if validlink %}

        <p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

        <form method="post">{% csrf_token %}
            <fieldset class="module aligned">
                <input class="hidden" autocomplete="username" value="{{ form.user.get_username }}">
                <div class="form-row field-password1">
                    {{ form.new_password1.errors }}
                    <div class="flex-container">
                        <label for="id_new_password1">{% translate 'New password:' %}</label>
                        {{ form.new_password1 }}
                    </div>
                </div>
                <div class="form-row field-password2">
                    {{ form.new_password2.errors }}
                    <div class="flex-container">
                        <label for="id_new_password2">{% translate 'Confirm password:' %}</label>
                        {{ form.new_password2 }}
                    </div>
                </div>
            </fieldset>
            <div class="submit-row">
                <input type="submit" value="{% translate 'Change my password' %}">
            </div>
        </form>

    {% else %}

        <p>{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

    {% endif %}

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" href="{% static "admin/css/forms.css" %}">{% endblock %}
{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
        &rsaquo; {% translate 'Password reset' %}
    </div>
{% endblock %}
{% block content %}

    <p>Забыли пароль?</p>
    <p> Введите свой адрес электронной почты ниже, и мы вышлем вам инструкцию, как установить новый пароль.</p>

    <form method="post">
        {% csrf_token %}
        <fieldset class="module aligned">
            <div class="form-row field-email">
                {{ form.email.errors }}
                <div class="flex-container">
{#                    <label for="id_email">{% translate 'Email address:' %}</label>#}
                    {{ form.email|as_crispy_field }}
                </div>
            </div>
        </fieldset>
        <div class="submit-row">
            <input type="submit" value="{% translate 'Reset my password' %}">
        </div>
    </form>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load django_github_tags %}
{% load user_tags %}

{% block link %}
{% endblock %}

{% block title %}
    Личный кабиннет
{% endblock %}

{% block content %}
    <section class="">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 mb-4 mb-sm-5">
                    <div class="card card-style1 border-0">
                        <div class="card-body p-1-9 p-sm-2-3 p-md-6 p-lg-7">
                            <div class="row align-items-center">
                                <div class="col-lg-6 mb-4 mb-lg-0">
                                    {% if user.photo %}
                                        <img src="{{ user.photo.url }}" alt=""
                                             class="avatar img-thumbnail">
                                    {% elif user.social_auth %}
                                        <img class="avatar img-thumbnail"
                                             src="https://github.com/{{ user.username }}.png" alt="">
                                    {% else %}
                                        <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="...">
                                    {% endif %}
                                </div>
                                <div class="col-lg-6 px-xl-10 bg-light h-100">
                                    <div class="d-lg-inline-block py-1-9 px-1-9 px-sm-6 mb-1-9 rounded">
                                        <h3 class="h2 text-dark mb-2 ">{{ request.user.first_name|title }}</h3>
                                    </div>
                                    <div class="d-flex ms-3">
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item bg-light fw-semibold">Статус:</li>
                                            <li class="list-group-item bg-light fw-semibold">Имя:</li>
                                            <li class="list-group-item bg-light fw-semibold">Фамилия:</li>
                                            <li class="list-group-item bg-light fw-semibold">E-mail:</li>
                                            <li class="list-group-item bg-light fw-semibold">Д/Р</li>
                                            <li class="list-group-item bg-light fw-semibold">Возраст:</li>
                                            <li class="list-group-item bg-light fw-semibold">Место рождения:</li>
                                        </ul>
                                        <ul class="list-group list-group-flush">
                                            {% if request.user.is_superuser %}
                                                <li class="list-group-item bg-light text-danger">админ</li>
                                            {% else %}
                                                <li class="list-group-item bg-light">пользователь</li>
                                            {% endif %}
                                            <li class="list-group-item bg-light">{{ request.user.first_name|title|default:'не заполнено' }}</li>
                                            <li class="list-group-item bg-light">{{ request.user.last_name|title|default:'не заполнено' }}</li>
                                            <li class="list-group-item bg-light">{{ request.user.email|default:'не заполнено' }}</li>
                                            <li class="list-group-item bg-light">{{ user.date_of_bird|date|default:'не заполнено' }}</li>
                                            <li class="list-group-item bg-light">{% total_year_users user.date_of_bird %}</li>
                                            <li class="list-group-item bg-light"><span src="123"></span></li>
                                        </ul>
                                    </div>
                                    <ul class="social-icon-style1 d-flex list-unstyled mt-3 ps-0">


                                        <li><a href="#!" class="p-2 text-danger fs-3"><i
                                                class="bi bi-pinterest"></i></a></li>
                                        <li><a href="#!" class="p-2 text-success fs-3"><i
                                                class="bi bi-whatsapp"></i></a></li>
                                        <li><a href="#!" class="p-2 text-primary fs-3"><i
                                                class="bi bi-telegram"></i></a></li>
                                        <li><a href="#!" class="p-2 text-dark fs-3"><i class="bi bi-github"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a href="{% url 'users:password_change' %}" class="btn btn-success">Сменить пароль</a>
        <a href="{% url 'users:profile_edit' %}" class="btn btn-success">Изменить личные данные</a>
    </section>
    {#    <img src=""  alt="https://github.com/{{ user.email }}">#}
{% endblock %}
{#                                <ul class="list-unstyled mb-1-9">#}
{#                                    <li class="mb-2"><span class="display-26 text-secondary me-2 ">Position:</span> Coach</li>#}
{#                                    <li class="mb-2"><span class="display-26 text-secondary me-2 ">Experience:</span> 10 Years</li>#}
{#                                    <li class="mb-2"><span class="display-26 text-secondary me-2 ">Email:</span> edith@mail.com</li>#}
{#                                    <li class="mb-2"><span class="display-26 text-secondary me-5 ">Website:</span> www.example.com</li>#}
{#                                    <li class="display-28"><span class="display-26 text-secondary me-2 font-weight-600">Phone:</span> 507 - 541 - 4567</li>#}
{#                                </ul>#}
{#                                <ul class="social-icon-style1 list-unstyled mb-0 ps-0">#}
{#                                    <li><a href="#!"><i class="fa-twitter-alt"></i></a></li>#}
{#                                    <li><a href="#!"><i class="ti-facebook"></i></a></li>#}
{#                                    <li><a href="#!"><i class="ti-pinterest"></i></a></li>#}
{#                                    <li><a href="#!"><i class="ti-instagram"></i></a></li>#}
{#                                </ul>#}